version: "3.7"
services:
  db:
    image: postgres:11.5
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=barkbot_dev
      - POSTGRES_USER=barkbot
      - POSTGRES_PASSWORD=password

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PROJECT_VERSION=${PROJECT_VERSION}
    depends_on:
      - db
